name: Website Deployment
on: [push, workflow_dispatch]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: node_module
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Lint code
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: node_module
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Test code
        id: run-tests
        run: npm run test
      - name: Upload test report
        if: failure() && steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: test.json
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: node_module
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build website
        id: build-website
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files
      - name: Output contents
        run: ls
      - name: Deploy
        run: echo "Deploying..."
  report:
    needs: [lint, deploy]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |
          echo "Something went wrong"
          echo "${{ toJSON(github) 

        
#Lint: This job runs on the latest version of Ubuntu and performs code linting. It checks for any code errors or style violations in the project. It retrieves the code, caches dependencies (unless already cached), installs dependencies, and then runs the linting process.

#Test: This job also runs on the latest version of Ubuntu. It retrieves the code, caches dependencies (unless already cached), installs dependencies, and runs tests. If the tests fail, it uploads the test report as an artifact.

#Build: This job depends on the completion of the Test job. It retrieves the code, caches dependencies (unless already cached), installs dependencies, and builds the website. The built files are then uploaded as artifacts.

#Deploy: This job depends on the completion of the Build job. It downloads the artifacts (built files) from the previous job, outputs their contents, and then performs the deployment. In the given code, it simply outputs the message "Deploying...".

#Report: This job depends on the completion of both the Lint and Deploy jobs. It runs only if any of the previous jobs failed. It outputs a message indicating that something went wrong and provides information about the GitHub context.
